const Types = {
  READ_POST_REQUEST: '@post/READ_POST_REQUEST',
  READ_POST_SUCCESS: '@post/READ_POST_SUCCESS',

  CREATE_POST_REQUEST: '@post/CREATE_POST_REQUEST',
  CREATE_POST_SUCCESS: '@post/CREATE_POST_SUCCESS',

  DELETE_POST_REQUEST: '@post/DELETE_POST_REQUEST',
  DELETE_POST_SUCCESS: '@post/DELETE_POST_SUCCESS',

  EDIT_POST_REQUEST: '@post/EDIT_POST_REQUEST',
  EDIT_POST_SUCCESS: '@post/EDIT_POST_SUCCESS',

  OPEN_MODAL_DELETE_POST: '@post/OPEN_MODAL_DELETE_POST',
  CLOSE_MODAL_DELETE_POST: '@post/CLOSE_MODAL_DELETE_POST',

  OPEN_MODAL_UPDATE_POST: '@post/OPEN_MODAL_UPDATE_POST',
  CLOSE_MODAL_UPDATE_POST: '@post/CLOSE_MODAL_UPDATE_POST',
}

export default Types
